# Feature selection

**Retrival the important feature selecting an important feature is very important steps before going to ML**
    
    - Droping the constant fetaures ( Regression and classification)

    - Information gain (Classification)

    - p-value (Regression)

    - VIF (Regression)

    - Forward selection and backward selection (Regression and classification)

    - Correlation with target column ( Regression and classification)

## Feature selection methods 

**1) Variance threshold:**
    
    - based on variance we can decide the data is constant or varying
  
    - Data is not varying much means , data has same  values
  
    - For example we have seen in loan dataset, loan term:360
  
    - Python by default will use variance=0, it will drop those fetaures which are having variance=0
  
    - Variance threshold is hyper parameter, we can keep threshold as any value
  
    - based on internal team discussion
  
    - we will drop those fetaure which are having <= threshold value

**2) P-value**   

    - H0: there is no relation x andy
        
    - H1: There is relation   X and Y
        
    - p<0.05     
    
        - Reject the Null hypothesis:  *Which means do not include the variable*
     
    - p>0.05
  
        - Not Reject the Null hypothesis: *which means include the variables*


**3)  Mutual info classify :** 
    
    - KNN and entropy

    - It will give the relation between input and output will pick which are having more relation

    - input vs output
    
        - 1) Entropy 
        
        - 2) KNN 
        
        - 3) R-square: explainability about y based on x

**4) Forward selection and backward selection**
     
     https://courses.lumenlearning.com/introstats1/chapter/model-selection/#:~:text=The%20forward%20selection%20strategy%20is,measured%20by%20adjusted%20R2).

   *Forward selection method*

       - Start with empty set of features
    
       - Iterate throuh each feature and select the one feature that improves model performance
    
       - Continue adding fetaures one by one till we meet our creteria

   *Backward selection mehod*

        - Start with full set of features
      
        - Iterate through each feature by removing the feature which is having less impact on the model
      
        - Continue the process, till your performance is stable
      
        - Both Forward selection and Bcakward selection methods are complex in nature
    
        - More time taken, will avoid in general
    
**5) *Variance inflation factor*(VIF):**

    - VIF will give the analysis of multicollinearity

    - In VIF will find the R-Square value of each input feature wrt to other input fetaure

    - Will keep one fetaure as input and  other fetaure are consider as output in Regression equation

    - This will keep on iterate through all fetaure

    - Every feature behave as input as well as output

    - As we know every regression line give Rsqurae value from that value will fine VIF

    - will drop the feature which are having VIF>5 or VIF >10 based on iternal team discussion

*Method-1 : variance threshold method*

    - if the feature or variance having zero variance 

    - the feature value throught out the data is the sane 

    - you can decide manually what is your desired variance in order to keep the feature 

In [1]:
import pandas as pd
dict1={'A':[100,200,300,400],
        'B':[1,2,3,4],
        'C':[10,20,30,40],
       'D':[10,10,10,10]}
df=pd.DataFrame(dict1)
df

A  B   C   D
0  100  1  10  10
1  200  2  20  10
2  300  3  30  10
3  400  4  40  10

In [3]:
import numpy as np
np.var(df['A'])

12500.0

In [5]:
import sklearn 
sklearn

<module 'sklearn' from 'C:\\Users\\vansh\\anaconda3\\Lib\\site-packages\\sklearn\\__init__.py'>

In [7]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
## threshold variance value 
# we want to drop the feature based on threshold 

vt.fit(df)

VarianceThreshold(threshold=0)

In [194]:
# fit means calculate the some thing 
# Transform means modify the data using that calculate value 
# Z=x-u/sigma
# fit mean it will calculate u and sigma

In [195]:
dir(vt)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_support_mask',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_transform',
 '_validate_data',
 '_validate_params',
 'feature_names_in_',
 'fit',
 'fit_tran

In [196]:
vt.variances_ 
# 300 is first column variance (T)
# 1.25 is second columns variance (T)
# 30 is column variance (T)
# 0 is forth column variance (F)

array([300.  ,   1.25,  30.  ,   0.  ])

In [197]:
vt.get_support()

array([ True,  True,  True, False])

In [11]:
df1=pd.read_csv('winequality_red.csv')
df1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [199]:
vt.fit(df1)

VarianceThreshold(threshold=0)

In [200]:
vt.variances_

array([3.02952057e+00, 3.20423261e-02, 3.79237511e-02, 1.98665392e+00,
       2.21375732e-03, 7.10000000e+01, 2.83000000e+02, 3.55980179e-06,
       2.38202742e-02, 2.87146470e-02, 1.13493717e+00, 6.51760540e-01])

In [201]:
# df1.drop_duplicates(inplace=True)
# df1.reset_index(drop=True,inplace=True)
# df1=df1.iloc[1:,:]


In [13]:
X=df1.drop('quality',axis=1)
y=df1['quality']
df1.shape,X.shape,y.shape

((1599, 12), (1599, 11), (1599,))

In [203]:
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
df=pd.read_csv('winequality_red.csv')
X=df.drop('quality',axis=1)
y=df['quality']
df.shape,X.shape,y.shape
vt.fit(X)
vt.variances_
vt.get_support()
cols=vt.get_feature_names_out()
X[cols]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

**the feature info classic file**

In [205]:
from sklearn.feature_selection import mutual_info_classif
ml=mutual_info_classif(X,y)
ml

array([0.05068229, 0.12821005, 0.09063691, 0.02370702, 0.0290005 ,
       0.0126463 , 0.06000417, 0.07994293, 0.01462676, 0.11723433,
       0.1595788 ])

In [206]:
d=pd.DataFrame(ml,index=X.columns,columns=['MI'])
sorted_data=d.sort_values(by='MI',ascending=False)
con=sorted_data['MI']>0.10
top=sorted_data[con]
final_cols=top.index
input=X[final_cols]
input

alcohol  volatile acidity  sulphates
0         9.4             0.700       0.56
1         9.8             0.880       0.68
2         9.8             0.760       0.65
3         9.8             0.280       0.58
4         9.4             0.700       0.56
...       ...               ...        ...
1594     10.5             0.600       0.58
1595     11.2             0.550       0.76
1596     11.0             0.510       0.75
1597     10.2             0.645       0.71
1598     11.0             0.310       0.66

[1599 rows x 3 columns]

In [207]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif
import pandas as pd
data=pd.read_csv('winequality_red.csv')
X=data.drop('quality',axis=1)
y=data['quality']

top_5=SelectKBest(mutual_info_classif,k=5)
val=top_5.fit(X,y)

In [208]:
val.get_support()

array([False,  True, False, False, False, False,  True,  True, False,
        True,  True])

In [209]:
val.get_feature_names_out()

array(['volatile acidity', 'total sulfur dioxide', 'density', 'sulphates',
       'alcohol'], dtype=object)